#!/usr/bin/env python3
# RunPod Serverless Handler for my-finetuned-model
# Auto-generated by deploy_model.py
#
# Deploy on: https://runpod.io/console/serverless
#
import runpod
from vllm import LLM, SamplingParams

sampling = SamplingParams(temperature=0.7, max_tokens=512)

def handler(job):
    job_input = job.get('input', {})
    prompt = job_input.get('prompt', '')
    max_tokens = job_input.get('max_tokens', 512)
    temperature = job_input.get('temperature', 0.7)

    if not prompt:
        return {'error': 'No prompt provided'}

    sp = SamplingParams(
        temperature=temperature,
        max_tokens=max_tokens,
        top_p=0.9,
    )

    global engine
    if 'engine' not in globals():
        engine = LLM(model='meta-llama/Llama-3.2-3B-Instruct')

    outputs = engine.generate([prompt], sp)
    result = outputs[0].outputs[0].text

    return {
        'output': result,
        'model': 'my-finetuned-model',
        'usage': {
            'prompt_tokens': len(outputs[0].prompt_token_ids),
            'completion_tokens': len(outputs[0].outputs[0].token_ids),
        },
    }

if __name__ == "__main__":
    runpod.serverless.start({"handler": handler})