#!/usr/bin/env python3
# Modal deployment for my-finetuned-model
# Auto-generated by deploy_model.py
#
# Usage:
#   modal deploy deploy_modal.py    # Deploy to Modal
#   modal run deploy_modal.py       # Run once (testing)
#
# Requires:
#   pip install modal
#
import modal

app = modal.App("my-finetuned-model")

# Define the image
image = (
    modal.Image.from_registry("nvidia/cuda:12.4.1-devel-ubuntu22.04", add_python="3.11")
    .pip_install(
        "vllm>=0.6.0",
        "fastapi",
        "uvicorn",
        "pydantic>=2.0",
    )
)

# GPU configuration
gpu = modal.gpu.A100(size="40GB", count=1)

@app.function(
    image=image,
    gpu=gpu,
    timeout=3600,
    min_containers=1,
    max_containers=4,
    container_idle_timeout=300,
)
@modal.asgi_app()
def vllm_server():
    from vllm.engine.arg_utils import AsyncEngineArgs
    from vllm.engine.async_llm_engine import AsyncLLMEngine
    from vllm.entrypoints.openai.api_server import build_app, init_app_state
    from fastapi import FastAPI

    app = FastAPI()

    @app.on_event("startup")
    async def startup():
        engine_args = AsyncEngineArgs(
            model="meta-llama/Llama-3.2-3B-Instruct",
            tensor_parallel_size=1,
            max_model_len=4096,
        )
        engine = AsyncLLMEngine.from_engine_args(engine_args)
        app.state.engine = engine

    @app.get("/v1/models")
    async def models():
        return {
            "object": "list",
            "data": [{"id": "my-finetuned-model", "object": "model"}],
        }

    @app.post("/v1/chat/completions")
    async def chat_completions():
        return {"message": "Not fully implemented - extend as needed"}

    return app


@app.local_entrypoint()
def main():
    print("Testing my-finetuned-model on Modal...")
    from vllm import LLM, SamplingParams
    llm = LLM(model="meta-llama/Llama-3.2-3B-Instruct")
    outputs = llm.generate(["Hello, world!"], SamplingParams(max_tokens=64))
    print(f"Output: {outputs[0].outputs[0].text}")