#!/usr/bin/env python3
# HuggingFace Spaces Gradio App for my-finetuned-model
# Auto-generated by deploy_model.py
#
# Deploy: Copy this directory to a new HF Space with GPU hardware.
#
import gradio as gr
from huggingface_hub import InferenceClient

MODEL_ID = "user/my-model"

def respond(message, chat_history, system_message, max_tokens, temperature, top_p):
    client = InferenceClient(MODEL_ID)

    messages = [{'role': 'system', 'content': system_message}]
    for user_msg, bot_msg in chat_history:
        messages.append({'role': 'user', 'content': user_msg})
        messages.append({'role': 'assistant', 'content': bot_msg})
    messages.append({'role': 'user', 'content': message})

    response = client.chat_completion(
        messages=messages,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
    )

    return response.choices[0].message.content

demo = gr.ChatInterface(
    respond,
    additional_inputs=[
        gr.Textbox('You are a helpful assistant.', label='System Message'),
        gr.Slider(1, 4096, value=512, step=1, label='Max Tokens'),
        gr.Slider(0.0, 2.0, value=0.7, step=0.1, label='Temperature'),
        gr.Slider(0.0, 1.0, value=0.9, step=0.05, label='Top-p'),
    ],
    title='my-finetuned-model',
    description='Fine-tuned model deployed on HuggingFace Spaces',
    theme=gr.themes.Soft(),
)

if __name__ == "__main__":
    demo.launch()